name: myapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.9.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # Google Generative AI SDK for Nano Banana (Gemini) image generation
  google_generative_ai: ^0.4.6

  # HTTP client for API calls
  http: ^1.2.0

  # State management
  provider: ^6.1.2

  # Video player for lesson videos
  video_player: ^2.9.3

  # Text-to-Speech for lesson narration
  flutter_tts: ^4.0.2

  # Audio player for sound effects
  audioplayers: ^6.0.0

  # Local storage for user progress
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/sounds/
    # Lesson images for all 28 days
    - assets/images/lessons/day1/lesson1/
    - assets/images/lessons/day1/lesson2/
    - assets/images/lessons/day1/lesson3/
    - assets/images/lessons/day1/lesson4/
    - assets/images/lessons/day1/lesson5/
    - assets/images/lessons/day1/test/
    - assets/images/lessons/day2/lesson1/
    - assets/images/lessons/day2/lesson2/
    - assets/images/lessons/day2/lesson3/
    - assets/images/lessons/day2/lesson4/
    - assets/images/lessons/day2/lesson5/
    - assets/images/lessons/day2/test/
    - assets/images/lessons/day3/lesson1/
    - assets/images/lessons/day3/lesson2/
    - assets/images/lessons/day3/lesson3/
    - assets/images/lessons/day3/lesson4/
    - assets/images/lessons/day3/lesson5/
    - assets/images/lessons/day3/test/
    - assets/images/lessons/day4/lesson1/
    - assets/images/lessons/day4/lesson2/
    - assets/images/lessons/day4/lesson3/
    - assets/images/lessons/day4/lesson4/
    - assets/images/lessons/day4/lesson5/
    - assets/images/lessons/day4/test/
    - assets/images/lessons/day5/lesson1/
    - assets/images/lessons/day5/lesson2/
    - assets/images/lessons/day5/lesson3/
    - assets/images/lessons/day5/lesson4/
    - assets/images/lessons/day5/lesson5/
    - assets/images/lessons/day5/test/
    - assets/images/lessons/day6/lesson1/
    - assets/images/lessons/day6/lesson2/
    - assets/images/lessons/day6/lesson3/
    - assets/images/lessons/day6/lesson4/
    - assets/images/lessons/day6/lesson5/
    - assets/images/lessons/day6/test/
    - assets/images/lessons/day7/lesson1/
    - assets/images/lessons/day7/lesson2/
    - assets/images/lessons/day7/lesson3/
    - assets/images/lessons/day7/lesson4/
    - assets/images/lessons/day7/lesson5/
    - assets/images/lessons/day7/test/
    - assets/images/lessons/day8/lesson1/
    - assets/images/lessons/day8/lesson2/
    - assets/images/lessons/day8/lesson3/
    - assets/images/lessons/day8/lesson4/
    - assets/images/lessons/day8/lesson5/
    - assets/images/lessons/day8/test/
    - assets/images/lessons/day9/lesson1/
    - assets/images/lessons/day9/lesson2/
    - assets/images/lessons/day9/lesson3/
    - assets/images/lessons/day9/lesson4/
    - assets/images/lessons/day9/lesson5/
    - assets/images/lessons/day9/test/
    - assets/images/lessons/day10/lesson1/
    - assets/images/lessons/day10/lesson2/
    - assets/images/lessons/day10/lesson3/
    - assets/images/lessons/day10/lesson4/
    - assets/images/lessons/day10/lesson5/
    - assets/images/lessons/day10/test/
    - assets/images/lessons/day11/lesson1/
    - assets/images/lessons/day11/lesson2/
    - assets/images/lessons/day11/lesson3/
    - assets/images/lessons/day11/lesson4/
    - assets/images/lessons/day11/lesson5/
    - assets/images/lessons/day11/test/
    - assets/images/lessons/day12/lesson1/
    - assets/images/lessons/day12/lesson2/
    - assets/images/lessons/day12/lesson3/
    - assets/images/lessons/day12/lesson4/
    - assets/images/lessons/day12/lesson5/
    - assets/images/lessons/day12/test/
    - assets/images/lessons/day13/lesson1/
    - assets/images/lessons/day13/lesson2/
    - assets/images/lessons/day13/lesson3/
    - assets/images/lessons/day13/lesson4/
    - assets/images/lessons/day13/lesson5/
    - assets/images/lessons/day13/test/
    - assets/images/lessons/day14/lesson1/
    - assets/images/lessons/day14/lesson2/
    - assets/images/lessons/day14/lesson3/
    - assets/images/lessons/day14/lesson4/
    - assets/images/lessons/day14/lesson5/
    - assets/images/lessons/day14/test/
    - assets/images/lessons/day15/lesson1/
    - assets/images/lessons/day15/lesson2/
    - assets/images/lessons/day15/lesson3/
    - assets/images/lessons/day15/lesson4/
    - assets/images/lessons/day15/lesson5/
    - assets/images/lessons/day15/test/
    - assets/images/lessons/day16/lesson1/
    - assets/images/lessons/day16/lesson2/
    - assets/images/lessons/day16/lesson3/
    - assets/images/lessons/day16/lesson4/
    - assets/images/lessons/day16/lesson5/
    - assets/images/lessons/day16/test/
    - assets/images/lessons/day17/lesson1/
    - assets/images/lessons/day17/lesson2/
    - assets/images/lessons/day17/lesson3/
    - assets/images/lessons/day17/lesson4/
    - assets/images/lessons/day17/lesson5/
    - assets/images/lessons/day17/test/
    - assets/images/lessons/day18/lesson1/
    - assets/images/lessons/day18/lesson2/
    - assets/images/lessons/day18/lesson3/
    - assets/images/lessons/day18/lesson4/
    - assets/images/lessons/day18/lesson5/
    - assets/images/lessons/day18/test/
    - assets/images/lessons/day19/lesson1/
    - assets/images/lessons/day19/lesson2/
    - assets/images/lessons/day19/lesson3/
    - assets/images/lessons/day19/lesson4/
    - assets/images/lessons/day19/lesson5/
    - assets/images/lessons/day19/test/
    - assets/images/lessons/day20/lesson1/
    - assets/images/lessons/day20/lesson2/
    - assets/images/lessons/day20/lesson3/
    - assets/images/lessons/day20/lesson4/
    - assets/images/lessons/day20/lesson5/
    - assets/images/lessons/day20/test/
    - assets/images/lessons/day21/lesson1/
    - assets/images/lessons/day21/lesson2/
    - assets/images/lessons/day21/lesson3/
    - assets/images/lessons/day21/lesson4/
    - assets/images/lessons/day21/lesson5/
    - assets/images/lessons/day21/test/
    - assets/images/lessons/day22/lesson1/
    - assets/images/lessons/day22/lesson2/
    - assets/images/lessons/day22/lesson3/
    - assets/images/lessons/day22/lesson4/
    - assets/images/lessons/day22/lesson5/
    - assets/images/lessons/day22/test/
    - assets/images/lessons/day23/lesson1/
    - assets/images/lessons/day23/lesson2/
    - assets/images/lessons/day23/lesson3/
    - assets/images/lessons/day23/lesson4/
    - assets/images/lessons/day23/lesson5/
    - assets/images/lessons/day23/test/
    - assets/images/lessons/day24/lesson1/
    - assets/images/lessons/day24/lesson2/
    - assets/images/lessons/day24/lesson3/
    - assets/images/lessons/day24/lesson4/
    - assets/images/lessons/day24/lesson5/
    - assets/images/lessons/day24/test/
    - assets/images/lessons/day25/lesson1/
    - assets/images/lessons/day25/lesson2/
    - assets/images/lessons/day25/lesson3/
    - assets/images/lessons/day25/lesson4/
    - assets/images/lessons/day25/lesson5/
    - assets/images/lessons/day25/test/
    - assets/images/lessons/day26/lesson1/
    - assets/images/lessons/day26/lesson2/
    - assets/images/lessons/day26/lesson3/
    - assets/images/lessons/day26/lesson4/
    - assets/images/lessons/day26/lesson5/
    - assets/images/lessons/day26/test/
    - assets/images/lessons/day27/lesson1/
    - assets/images/lessons/day27/lesson2/
    - assets/images/lessons/day27/lesson3/
    - assets/images/lessons/day27/lesson4/
    - assets/images/lessons/day27/lesson5/
    - assets/images/lessons/day27/test/
    - assets/images/lessons/day28/lesson1/
    - assets/images/lessons/day28/lesson2/
    - assets/images/lessons/day28/lesson3/
    - assets/images/lessons/day28/lesson4/
    - assets/images/lessons/day28/lesson5/
    - assets/images/lessons/day28/test/
    # Videos
    - assets/videos/lessons/day2/
    - assets/videos/lessons/day2/lesson1/
    - assets/videos/lessons/day2/lesson2/
    - assets/videos/lessons/day2/lesson3/
    - assets/videos/lessons/day2/lesson4/
    - assets/videos/lessons/day2/lesson5/
    - assets/videos/lessons/day2/test/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
